### ISSUE TITLE
TODO QW* class

### ISSUE THREAD

**Issue by zccrs** [vioken/qwlroots#19]
- [x] QWDisplay https://github.com/vioken/qwlroots/pull/22
- [x] QWSeat https://github.com/vioken/qwlroots/pull/27
- [ ] QWSurface
- [x] QWKeyboard https://github.com/vioken/qwlroots/pull/44
- [x] QWPointer https://github.com/vioken/qwlroots/pull/45
- [ ] QWSwitch
- [ ] QWTouch
- [x] QWTablet https://github.com/vioken/qwlroots/pull/48
- [x] QWTabletPad https://github.com/vioken/qwlroots/pull/48
- [ ] QWSession
- [ ] QW*Interface https://github.com/vioken/qwlroots/pull/42
- [ ] QWOutputDamage
- [ ] QWRenderPass
- [ ] QWSwapchain

**Comment by wineee** [comment]
Doing:
- [ ] QWKeyboard
- [ ] QWInputDevice
