### ISSUE TITLE
TODO: add types to support 0.18

### ISSUE THREAD

**Issue by ZhongYic00** [vioken/qwlroots#236]
- [ ] QWSession for wlr_session (qwbackend.cpp)
- [ ] QWDevice for wlr_device (qwbackend.cpp)
- [ ] QWRenderPass for wlr_render_pass (qwrenderer.h)
- [ ] QWOutputLayoutOutput for wlr_output_layout_output (qwoutputlayout.h)
- [ ] QWSeatClient for wlr_seat_client (qwseat.cpp)
